options:
  cpuset:
    type: string
    default: ''
    description: |
      The set of CPUs on which the SPDK target may run. This can be
      an integer, which specifies the number of cores, or a squared-bracketed
      list of CPU id's.

  proxy-port:
    type: int
    default: 64321
    description: |
      The port on which the internal proxy will be bound to.
